"use client";

import { useEffect, useRef } from "react";
import QRCodeStyling from "qr-code-styling";
import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useTheme } from "next-themes"; // Import theme hook

interface QRCodeCardProps {
  data: string;
  healthHex: string; // NEW: The hex code generated by your health function
  logoUrl?: string;
}

export function QRCodeCard({ data, healthHex, logoUrl }: QRCodeCardProps) {
  const ref = useRef<HTMLDivElement>(null);
  const qrCode = useRef<QRCodeStyling | null>(null);
  const { resolvedTheme } = useTheme(); // Resolves 'system' to 'dark' or 'light'

  useEffect(() => {
    if (!resolvedTheme) return; // Wait for theme to hydrate

    // Determine Base Contrast Color
    // Dark mode = White (#ffffff), Light mode = Dark Slate/Black (#0f172a)
    const baseColor = resolvedTheme === "dark" ? "#ffffff" : "#0f172a";

    // Initialize QR Code Styling with dynamic colors
    qrCode.current = new QRCodeStyling({
      width: 200,
      height: 200,
      type: "svg",
      data: data,
      image: logoUrl,
      // --- COLOR MIXING LOGIC ---
      // Dots use the base color (White/Black)
      dotsOptions: {
        color: baseColor, 
        type: "rounded",
      },
      // Corner squares use the health color (Green/Red/Yellow)
      cornersSquareOptions: {
        color: healthHex,
        type: "extra-rounded",
      },
      // Corner dots inside squares use the base color
      cornersDotOptions: {
        color: baseColor,
      },
      backgroundOptions: {
        color: "transparent",
      },
      imageOptions: {
        crossOrigin: "anonymous",
        margin: 10,
      },
    });

    if (ref.current) {
      ref.current.innerHTML = "";
      qrCode.current.append(ref.current);
    }
  }, [data, logoUrl, resolvedTheme, healthHex]); // Re-render if theme or health changes

  const handleDownload = () => {
    qrCode.current?.download({
      name: "loan-portfolio-qr",
      extension: "png",
    });
  };

  return (
    <div className="flex flex-col items-center justify-center h-full gap-4">
      {/* Container adapts background based on theme for better QR scanning contrast */}
      <div 
        ref={ref} 
        className="p-4 rounded-xl border border-border shadow-inner bg-background"
      />
      <div className="text-center space-y-2">
        <Button 
          variant="outline" 
          size="sm" 
          className="h-8 text-xs gap-2"
          onClick={handleDownload}
        >
          <Download className="h-3 w-3" /> Save QR
        </Button>
      </div>
    </div>
  );
}